const SCREEN = {
    BOTTOM_TAB: 'BOTTOM_TAB',
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN',
    USER_SCREEN: 'USER_SCREEN',
    MESSAGES_SCREEN: 'MESSAGES_SCREEN',
    MY_NETWORK_SCREEN:'MY_NETWORK_SCREEN',
    REGISTER_SCREEN: 'REGISTER_SCREEN',
    LAYPASS_SCREEN: 'LAYPASS_SCREEN',
    TEXTPASS_SCREEN: 'TEXTPASS_SCREEN',
};
export default SCREEN;